services:
  nuxt-test:
    build: .
    image: clangroth/eden-labs:staging
    container_name: nuxt-test
    restart: always
    networks:
      - traefik_default
    env_file:
      - .env.staging
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nuxt-test.rule=Host(`test.eden-labs.fr`)"
      - "traefik.http.routers.nuxt-test.entrypoints=websecure"
      - "traefik.http.routers.nuxt-test.tls=true"
      - "traefik.http.routers.nuxt-test.tls.certresolver=myresolver"
      - "traefik.http.services.nuxt-test.loadbalancer.server.port=3000"
      - "traefik.http.routers.nuxt-test.middlewares=authelia@docker"

networks:
  traefik_default:
    external: true