name: Déploiement Production

on:
  push:
    branches:
      - master

jobs:
  deploy-production:
    name: Déploiement Production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://eden-labs.fr

    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v3

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Se connecter à DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Sauvegarde de l'image actuelle en taggant "previous"
        run: |
          docker pull clangroth/eden-labs:latest || echo "Pas d'image précédente"
          docker tag clangroth/eden-labs:latest clangroth/eden-labs:previous
          docker push clangroth/eden-labs:previous

      - name: Build et Push de la nouvelle image Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: clangroth/eden-labs:latest

      - name: Déploiement sur le VPS via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull clangroth/eden-labs:latest
            docker compose -f /opt/eden-labs/docker-compose.production.yml up -d

      - name: Vérification de la disponibilité
        run: |
          echo "Attente de 10 secondes"
          sleep 10
          curl -f https://eden-labs.fr
        continue-on-error: true

      - name: Rollback en cas d'échec
        if: ${{ failure() }}
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Le déploiement a échoué, lancement du rollback..."
            /opt/eden-labs/rollback.sh
