name: Déploiement Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging:
    name: Déploiement Staging
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code source
        uses: actions/checkout@v3

      - name: Configurer Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Se connecter à DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build et Push de l'image Docker (staging)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: clangroth/eden-labs:staging

      - name: Déploiement sur le VPS via SSH (Staging)
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull clangroth/eden-labs:staging
            docker compose -f /opt/nuxt-test/docker-compose.staging.yml up -d
